apiVersion: v1
kind: ConfigMap
metadata:
  name: java-cloud-platform-lab-datasource-config
  labels:
    app: java-cloud-platform-lab
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres.example.local:5432/cloudlab
