apiVersion: v1
kind: Secret
metadata:
  name: java-cloud-platform-lab-datasource-secret
  labels:
    app: java-cloud-platform-lab
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: cloudlab
  SPRING_DATASOURCE_PASSWORD: cloudlab
