apiVersion: v1
kind: Service
metadata:
  name: java-cloud-platform-lab
  labels:
    app: java-cloud-platform-lab
spec:
  type: ClusterIP
  selector:
    app: java-cloud-platform-lab
  ports:
    - name: http
      port: 8080
      targetPort: 8080
